version: "0.0.1"

services:
  redis:
    image: redis:latest
    container_name: redis
    ports:
      - "6379:6379"  # пробрасываем Redis наружу

  app:
    build: .
    container_name: tinyurl-app
    ports:
      - "8000:8000"  # FastAPI наружу на localhost:8000
    env_file:
      - .env
    depends_on:
      - redis
    volumes:
      - .:/app
